### ISSUE TITLE
Generater.exe stops working

### ISSUE THREAD

**Issue by dkdkfjgh** [Babumi/DesktopCharacter#80]
Hi! I'm trying to download DesktopCharacter to my local PC and trying to compile it.
Everything is working but when I execute the BatchFiles\CreateLive2dfordll.bat, Generater.exe stops working with ArgumentNullException.

Here is the stacktrace for the Generater.exe -
  Unhandled Exception: System.ArgumentNullException: Value cannot be null.
  Parameter name: path1
     at System.IO.Path.Combine(String path1, String path2)
     at CppSharp.MSVCToolchain.CollectUniversalCRuntimeIncludeDirs(String vsDir
  , ToolchainVersion windowsKitSdk, Int32 windowsSdkMajorVer)
     at CppSharp.MSVCToolchain.GetSystemIncludes(VisualStudioVersion vsVersion)
     at CppSharp.OptionsExtensions.SetupMSVC(ParserOptions options, VisualStudi
  oVersion vsVersion)
     at CppSharp.Driver.SetupIncludes()
     at CppSharp.Driver.Setup()
     at CppSharp.ConsoleDriver.Run(ILibrary library)
     at Generater.Program.Main(String[] args) in C:\Live2DPlay\DesktopCharacter
  \Extension\Generater\Program.cs:line 15

OS : Windows 7 SP1(x64)
Live2D SDK Version : Live2D_SDK_OpenGL_2.1.02.3_en
Visual Studio Version : 2013, 2015

**Comment by KirisameMarisa** [comment]
Reported Thank you for!

"Windows SDK 10" might not have been installed.
"C: \ Program Files (x86) \ Windows Kits \ 10" or would you have any?

Please try to install it from here.
"Https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk"
Document was also updated.

Thank you.

**Comment by dkdkfjgh** [comment]
It worked after installing Windows SDK 10. Thanks for your help!

**Comment by KirisameMarisa** [comment]
Action reporting Thank you.
Together let's be healed!(っ ´-` c)

**Comment by KirisameMarisa** [comment]
I English of the document will be created in the near future. ⇒ #81
